version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9.13
    steps:
      - checkout
      - run: python --version
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python python3 -m pytest test.py
  package:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .