version: 2.1
orbs:
  helm: circleci/helm@1.0
  
jobs:
  build-test:
    docker:
      - image: cimg/python:3.9.13
    steps:
      - checkout
      - run: python --version
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            pip install pytest
            python -m pytest test.py
  build-push-scan-Image:
    environment:
      IMAGE_NAME: docker.io/thywoe/crypto-rates
    docker:
      - image: docker:17.05.0-ce-git
    steps:

      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          name: Build and push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $IMAGE_NAME:$TAG .
            docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME:$TAG 
            docker push $IMAGE_NAME:latest 
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan the local image with trivy
          command: trivy image --exit-code 1 --severity HIGH,CRITICAL -f table $IMAGE_NAME:$TAG

  # packageHelm:
  #   executor: <<parameters.executor>>
  #   resource_class: small
  #   parameters:
  #     charts-dir:
  #       default: crypto-rates
  #       description: Path of helm chart(s)
  #       type: string
  #     add-extra-repositories:
  #       default: [https://thywoe.github.io/crypto-rates-app/]
  #       description: Steps to add extra repositories
  #       type: steps
  #     tgz-dir:
  #       default: /workspace/tgz
  #       description: Directory of chart tgz
  #       type: string
  #     skip-dependency-update:
  #       type: boolean
  #       default: false
  #     executor:
  #       default: helm3
  #       description: Executor to use
  #       type: executor

  #   steps:
  #     - checkout
  #     - setup-repositories:
  #         add-extra-repositories: << parameters.add-extra-repositories >>
  #     - check-parameters:
  #         charts-dir: << parameters.charts-dir >>
  #     - unless:
  #         condition: << parameters.skip-dependency-update >>
  #         steps:
  #           - update-dependencies:
  #               charts-dir: << parameters.charts-dir >>
  #     - lint:
  #         charts-dir: << parameters.charts-dir >>
  #     - build:
  #         charts-dir: << parameters.charts-dir >>
  #         tgz-dir: <<parameters.tgz-dir >>
  #     - publish:
  #         tgz-dir: <<parameters.tgz-dir >>
    # docker:
    #     - image: alpine/helm:latest
    # steps:
    #   - checkout
    #   - run:
    #       name: Package and Deploy helm charts
    #       command: |
    #         helm package crypto-rates
    #         helm push crypto-rates-repo-0.1.0.tgz https://thywoe.github.io/crypto-rates-app/


workflows:
  build_and_package_workflow:
    jobs:
      - build-test
      - build-push-scan-Image:
          requires:
            - build-test
      # - packageHelm
      - helm/publish-chart:
          context: helm
          charts-dir: crypto-rates
          add-extra-repositories:
            - run: "helm repo add extra \thttps://thywoe.github.io/crypto-rates-app"
          # requires:
          #   - build-push-scan-Image
