version: 2.1
orbs:
  helm: circleci/helm@1.0
  
jobs:
  build-test:
    docker:
      - image: cimg/python:3.9.13
    steps:
      - checkout
      - run: python --version
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            pip install pytest
            python -m pytest test.py
  build-push-Image:
    environment:
      IMAGE_NAME: docker.io/thywoe/crypto-rates
    docker:
      - image: docker:17.05.0-ce-git
    steps:

      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          name: Build and push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $IMAGE_NAME:$TAG .
            docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME:$TAG 
            docker push $IMAGE_NAME:latest 
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan the local image with trivy
          command: trivy --exit-code 1 --no-progress $IMAGE_NAME:$TAG

  packageHelm:
    docker:
        - image: circleci/golang:1.10
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Install and configuire helm
          command: sudo curl -L https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz | tar xz && sudo mv linux-amd64/helm /bin/helm && sudo rm -rf linux-amd64

workflows:
  build_and_package_workflow:
    jobs:
      - build-test
      - build-push-Image:
          requires:
            - build-test
      - packageHelm:
          requires:
            - build-push-Image

