version: 2.1
orbs:
  helm: circleci/helm@1.0
  
jobs:
  build-test:
    docker:
      - image: cimg/python:3.9.13
    steps:
      - checkout
      - run: python --version
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            pip install pytest
            python -m pytest test.py
  build-push-scan-Image:
    environment:
      IMAGE_NAME: docker.io/thywoe/crypto-rates
    docker:
      - image: docker:17.05.0-ce-git
    steps:

      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          name: Build and push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $IMAGE_NAME:$TAG .
            docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME:$TAG 
            docker push $IMAGE_NAME:latest 
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan the local image with trivy
          command: trivy image --exit-code 1 --severity HIGH,CRITICAL -f table $IMAGE_NAME:$TAG

  packageHelm:
    docker:
        - image: alpine/helm:latest
    steps:
      - checkout
      - run:
          name: Package and Deploy helm charts
          command: |
            helm plugin install https://github.com/chartmuseum/helm-push
            helm package crypto-rates
            #helm repo add https://thywoe.github.io/crypto-rates-app/
            helm repo add --username $DOCKER_USER --password  $DOCKER_PASS project-1 https://thywoe.github.io/crypto-rates-app/
            helm cm-push crypto-rates-0.1.0.tgz project-1

workflows:
  build_and_package_workflow:
    jobs:
      - build-test
      - build-push-scan-Image:
          requires:
            - build-test
      - packageHelm
          # requires:
          #   - build-push-scan-Image

