name: testing github actions

on:
  push:
    branches:
      - "main"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
      - name: checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: test
        run: 